### ISSUE TITLE
generate-yaml.sh failed with "./generate-yaml.sh: 100: read: Illegal option -s"

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#81]
generate-yaml.sh failed with "./generate-yaml.sh: 100: read: Illegal option -s" on Ubuntu.
Bacause Ubuntu default shell is dash which does not support read with -s option.

Shebang of generate-yaml.sh should be /bin/bash instead of /bin/sh.

**Comment by Lion-Wei** [comment]
Hi, @hidekazuna , thanks for raising this. 
But I don't think `/bin/sh` lead to your problem, this script works well in my environment(Ubuntu 16.04). Can you offer more information?

**Comment by hidekazuna** [comment]
@Lion-Wei , thanks for your response.

Here is the result I executed on 18.04.1 LTS (Bionic Beaver).
```shell
ubuntu@u1804:~/go/src/sigs.k8s.io/cluster-api-provider-openstack/cmd/clusterctl/examples/openstack$ ./generate-yaml.sh
Enter your username:hidekazuna
Enter your domainname:Default
Enter your project id:c4c46338daa44ff199b40b57a6e55a85
Enter region name:RegionOne
Enter authurl: http://192.168.50.28:5000/v3
./generate-yaml.sh: 100: read: Illegal option -s
ubuntu@u1804:~/go/src/sigs.k8s.io/cluster-api-provider-openstack/cmd/clusterctl/examples/openstack$
```

**Comment by chrigl** [comment]
The default `/bin/sh` in ubuntu is `dash`, which does not implement -s on read.  It fails on a clean ubuntu 16.04 as well. There are other places where `generate-yaml.sh` fails. dash also does not implement `[[`.

```
ubuntu@openstack-master-m2h8q:~/cluster-api-provider-openstack/cmd/clusterctl/examples/openstack$ uname -a
Linux openstack-master-m2h8q 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@openstack-master-m2h8q:~/cluster-api-provider-openstack/cmd/clusterctl/examples/openstack$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Feb 17  2016 /bin/sh -> dash

ubuntu@openstack-master-m2h8q:~/cluster-api-provider-openstack/cmd/clusterctl/examples/openstack$ ./generate-yaml.sh
Enter your username:test
Enter your domainname:test
Enter your project id:test
Enter region name:tes
Enter authurl:test
./generate-yaml.sh: 100: read: Illegal option -s

ubuntu@openstack-master-m2h8q:~/cluster-api-provider-openstack/cmd/clusterctl/examples/openstack$ dash
$ [[ -z "" ]]
dash: 1: [[: not found
```

**Comment by dims** [comment]
+1 to change shebang to /bin/bash to be specific that we depend on bash

**Comment by hidekazuna** [comment]
/assign @hidekazuna 

I will fix this for my first issue.
