### ISSUE TITLE
ipam.cluster.x-k8s.io/v1beta2 in capo version <= v0.13.1

### ISSUE THREAD

**Issue by shreekantpk** [kubernetes-sigs/cluster-api-provider-openstack#2935]
/kind bug

**What steps did you take and what happened:**
I am using the capi version v1.10.10 and capo version v0.13.1 (I've seen that `ipam.cluster.x-k8s.io/v1beta1` is removed from capo v13.2 ) - I also tried to run capo version v0.13.0 with no luck

The combination should have worked but the capo manager is not running and fails with the error: 
`E0108 14:06:10.471946       1 main.go:326] "unable to create controller" err="unable to retrieve the complete list of server APIs: ipam.cluster.x-k8s.io/v1beta2: no matches for ipam.cluster.x-k8s.io/v1beta2, Resource=" logger="setup" controller="FloatingIPPool"`

**What did you expect to happen:**
capo-manager should be running (k8s.gcr.io/capi-openstack/capi-openstack-controller:v0.13.1)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Versions/logs attached
```
➜  ~ k get InfrastructureProvider -A 
NAMESPACE                NAME        INSTALLEDVERSION   READY
muon-tenant-capi-mgmnt   openstack   v0.13.0            False
➜  ~ k get ControlPlaneProvider -A   
NAMESPACE                NAME      INSTALLEDVERSION   READY
dev-capi-mgmnt           kubeadm   v1.10.10           True
➜  ~ k get BootstrapProvider -A 
NAMESPACE                NAME      INSTALLEDVERSION   READY
dev-capi-mgmnt           kubeadm   v1.10.10           True
➜  ~ k get CoreProvider -A  
NAMESPACE                NAME          INSTALLEDVERSION   READY
dev-capi-mgmnt           cluster-api   v1.10.10           True
➜  ~ k get pods -A | grep cap
capi-operator-system    capi-operator-controller-manager-66d4fdc4dd-f7bkr                1/1     Running            0             23m
dev-capi-mgmnt          capi-controller-manager-744b49d674-vc5f4                         1/1     Running            0             22m
dev-capi-mgmnt          capi-kubeadm-bootstrap-controller-manager-5497db48bb-gvhfm       1/1     Running            0             22m
dev-capi-mgmnt          capi-kubeadm-control-plane-controller-manager-5d67d5b944-h56rr   1/1     Running            0             22m
dev-capi-mgmnt          capo-controller-manager-7f9ff58c76-x6llc                         0/1     CrashLoopBackOff   12 (78s ago)  22m

➜  ~ k logs -n dev-capi-mgmnt  capo-controller-manager-7f9ff58c76-x6llc
I0108 14:40:11.443386       1 envvar.go:172] "Feature gate default state" feature="InOrderInformers" enabled=true
I0108 14:40:11.443440       1 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I0108 14:40:11.443444       1 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false
I0108 14:40:11.443448       1 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I0108 14:40:11.443451       1 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
E0108 14:40:11.459986       1 main.go:326] "unable to create controller" err="unable to retrieve the complete list of server APIs: ipam.cluster.x-k8s.io/v1beta2: no matches for ipam.cluster.x-k8s.io/v1beta2, Resource=" logger="setup" controller="FloatingIPPool"
➜  ~ k api-versions | grep ipam
ipam.cluster.x-k8s.io/v1alpha1
ipam.cluster.x-k8s.io/v1beta1
➜  ~ 


```

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.13.0 and :v0.13.1
- Cluster-API version: v1.10.10
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): v1.30.0
- OS (e.g. from `/etc/os-release`):

**Comment by shreekantpk** [comment]
It works well with `v0.12.6` btw, I just checked so this issue only on `v0.13.0` and `v0.13.1`

**Comment by lentzi90** [comment]
CAPO v0.13 requires CAPI v1.11 or newer because of the new v1beta2 API.

**Comment by mstrohl** [comment]
We've got the same error using v0.13.2 that should fallback to v1beta1 for backward compatibility if I understand well the following note in the release note : 

> NOTE: Pervious releases of v0.13 (v0.13.0 and v0.13.1) incorrectly
advertised v1beta2 contract support in the metadata.yaml. This has been fixed in
this version. CAPO v0.13 does NOT fully implement v1beta2 and CAPI will in fact
use v1beta1 with it. We do however test CAPI's v1beta2 API and it works well
together with CAPO since there is still backwards compatibility with the v1beta1
contract.

**Comment by lentzi90** [comment]
Sorry for the confusion, CAPO requires a v1beta2 version of CAPI, but does not implement the v1beta2 contract fully yet. So CAPI will use the v1beta1 contract for CAPO. However, CAPO depends on the v1beta2 API version from CAPI.

CAPI v1.11 and v1.12 still has backwards compatibility for v1beta1 so they can work with CAPO using the v1beta1 contract. They also implement the v1beta2 API version, and CAPO makes use of this (e.g. reading CAPI objects with this version).

**Comment by faelis** [comment]
@lentzi90 I have a similar problem :
- I can't upgrade to capi 1.11+ because my other provider are not compatible, so I have to stay on capo 0.12.x
- I need k-orc 2.3+ because it enable the image community visibility feature, but k-orc 2.3+ is used in capo 0.13.x
Is there any chance to have a capo 0.12.7 version with k-orc 2.3+ ? Or could explain how to achieve it by ourselves?

Regards

**Comment by lentzi90** [comment]
Unfortunately we cannot do that. With k-orc 2.3 we would need to bump also k8s.io and controller-runtime dependencies. This is too much and could become an issue for people importing our code (as opposed to just deploying CAPO in a cluster).

**Comment by akrause2014** [comment]
I have upgraded to v0.13.2 and was still running v1.10.10 of CAPI and I'm getting the same error. Reading this issue, CAPI v1.11 should fix this, however `clusterctl upgrade plan` does not show any available updates
```
Checking new release availability...

Latest release available for the v1beta1 Cluster API contract version:

NAME                       NAMESPACE                           TYPE                     CURRENT VERSION   NEXT VERSION
bootstrap-kubeadm          capi-kubeadm-bootstrap-system       BootstrapProvider        v1.10.10          Already up to date
control-plane-kubeadm      capi-kubeadm-control-plane-system   ControlPlaneProvider     v1.10.10          Already up to date
cluster-api                capi-system                         CoreProvider             v1.10.10          Already up to date
infrastructure-openstack   capo-system                         InfrastructureProvider   v0.13.2           Already up to date
```
How do I now upgrade to v1.11?

**Comment by lentzi90** [comment]
Hmm, could it be that you have an old version of `clusterctl`?

**Comment by akrause2014** [comment]
> Hmm, could it be that you have an old version of `clusterctl`?

I ran this before and it offered me both `v1beta1` and `v1beta2` upgrades but after the `v1beta1` upgrade it stopped showing `v1beta2`. I downloaded the latest version to make sure
```
clusterctl version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"b9b906573c236b661c2b9565be6fefcdecfc99d2", GitTreeState:"clean", BuildDate:"2025-12-18T13:14:08Z", GoVersion:"go1.24.11", Compiler:"gc", Platform:"linux/amd64"}
```
and I'm getting the same output.

Fixed with `upgrade apply --bootstrap=kubeadm:v1.11.4 --control-plane=kubeadm:v1.11.4 --core=cluster-api:v1.11.4`
